project/urls.py
from django.contrib import admin
from django.urls import path, include
from quiz import views as quiz_views

urlpatterns = [
    path("", quiz_views.main, name="main"),
    path("admin/", admin.site.urls),
    path("user/", include("user.urls")),
    path("football_quiz/", include("quiz.urls")),
]

quiz/urls.py
from django.urls import path
from quiz import views

app_name = "football_quiz"

urlpatterns = [
    path("", views.main, name="main"),
    path("quiz/", views.main_quiz, name="main_quiz"),
    path("squad/", views.main_squad, name="main_squad"),
    path("quiz/<str:quiz_type>/", views.quiz, name="quiz"),
    path(
        "squad_challange/<str:quiz_type>/", views.squad_challange, name="squad_challange"
    ),
    path("<str:quiz_type>/result/", views.result, name="result"),
    path("ranking/<str:quiz_type>/", views.ranking, name="ranking"),
    path("profile/<int:user_id>/", views.profile, name="profile"),
]

user/urls.py
from django.urls import path
from user import views

app_name = "user"

urlpatterns = [
    path("register/", views.register_request, name="register_request"),
    path("login/", views.login_request, name="login_request"),
    path("logout/", views.logout_request, name="logout_request"),
]

quiz/models.py
from django.db import models
from django.conf import settings
from django.utils.timezone import now
from sqlalchemy import UniqueConstraint


class Quiz(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="Quiz_user",
        blank=True,
        null=True,
    )
    quiz_type = models.CharField(max_length=20)
    score = models.IntegerField()
    date = models.DateTimeField(default = now())
    __table_args__ = (
        UniqueConstraint(
            "score", "user", "quiz_type", name="unique_score_user_quiz_type"
        ),
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user", "quiz_type", "score"],
                name="unique_score_user_quiz_type",
            )
        ]

    def __str__(self):
        return f"User: {self.user} got: {self.score} in quiz: {self.quiz_type}"

    def save(self, *args, **kwargs):
        if Quiz.objects.filter(
            user=self.user, quiz_type=self.quiz_type, score=self.score
        ).exists():
            # Existing quiz found, update the date instead of creating a new entry
            self.date = now()
        else:
            # No existing quiz found, create a new entry
            super().save(*args, **kwargs)

user/models.py
from django.db import models

# Create your models here.

quiz/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from quiz.models import Quiz
from quiz.squad_manager import SquadManager
from quiz.quiz_manager import get_info, get_quiz_result
from utils.logger import configure_logger
logger = configure_logger()


def main(request):
    context = {}
    return render(request, template_name="quiz/menu_main.html", context=context)


def main_quiz(request):
    return render(request, template_name="quiz/menu_quiz.html")


def main_squad(request):
    return render(request, template_name="quiz/menu_squad.html")


def quiz(request, quiz_type):
    data = get_info(quiz_type)
    context = {
        "quiz_type": quiz_type,
        "teams": data[0],
        "first_date": data[1],
        "last_date": data[2],
        "competition": data[3],
        "questions": data[4],
    }
    return render(request, template_name="quiz/quiz.html", context=context)


def squad_challange(request, quiz_type):
    data = SquadManager.info(quiz_type)
    # Getting info of 300 best matches for each position and shuffling
    context = {
        "attack": data.loc[data["position"] == "Attack", "name"]
        .iloc[:300]
        .sample(frac=1),
        "middlefielder": data.loc[data["position"] == "Midfield", "name"]
        .iloc[:300]
        .sample(frac=1),
        "defender": data.loc[data["position"] == "Defender", "name"]
        .iloc[:300]
        .sample(frac=1),
        "goalkeeper": data.loc[data["position"] == "Goalkeeper", "name"]
        .iloc[:300]
        .sample(frac=1),
        "quiz_type": quiz_type,
    }
    return render(request, template_name="quiz/squad.html", context=context)


def result(request, quiz_type):
    context = {"score": 0}
    if request.method == "POST":
        # Checking type of posted quiz
        if "goalkeeper" in request.POST.keys():
            score = SquadManager.get_squad_result(quiz_type, request.POST)
        else:
            score = get_quiz_result(quiz_type, items=request.POST.items())
        # Saving result
        user = request.user if request.user.is_authenticated else None
        result_object = Quiz.objects.create(user=user, quiz_type=quiz_type, score=score)
        logger.debug(f"{result_object}")
        context = {"score": result_object}
    return render(request, template_name="quiz/result.html", context=context)


def ranking(request, quiz_type):
    # Checking if user ask for specific rank
    if quiz_type == "all":
        context = {
            "quiz_type": "All",
            "result": Quiz.objects.all().order_by("score").reverse,
        }
    else:
        context = {
            "quiz_type": quiz_type,
            "result": Quiz.objects.filter(quiz_type=quiz_type)
            .order_by("score")
            .reverse,
        }
    return render(request, template_name="quiz/ranking.html", context=context)


def profile(request, user_id):
    context = {
        "profile": User.objects.get(id=user_id),
        "result": Quiz.objects.filter(user=user_id)
        .order_by("quiz_type", "score")
        .reverse,
    }
    return render(request, template_name="quiz/profile.html", context=context)

user/views.py
from django.urls import reverse
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from utils.logger import configure_logger

logger = configure_logger()


def register_request(request):
    context = {}
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["psw"]
        first_name = request.POST["firstname"]
        last_name = request.POST["lastname"]
        try:
            User.objects.get(username=username)
            messages.error(request, "User already exists")
            return redirect(reverse("user:register_request"))
        except User.DoesNotExist:
            user = User.objects.create_user(
                username=username,
                first_name=first_name,
                last_name=last_name,
                password=password,
            )
            login(request, user)
            logger.debug(f"Register user: {username}")
            messages.success(request, "Successfully registered!")
            return redirect(reverse("football_quiz:main"))
    return render(request, "user/register.html", context=context)


def login_request(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["psw"]
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            logger.debug(f"Login user: {username} ")
            messages.success(request, "Successfully logged in!")
            return redirect(reverse("football_quiz:main"))
        else:
            messages.error(request, "Invalid username or password")
            return redirect(reverse, "football_quiz:main")
    return render(request, "user/login.html")


def logout_request(request):
    logger.debug(f"Logout user: {request.user.username}")
    logout(request)
    messages.success(request, "Successfully logged out!")
    return redirect(reverse("football_quiz:main"))

quiz/templates/quiz/index.html
<!doctype html>
<html lang="en">
   <head>
      {% load static %}
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="description" content="This is a Django App for Football Quiz"/>
      <meta name="author" content="Kamil Falkowski" />
      <title>{% block title %}Football Quiz{% endblock%}</title>
      <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
         integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
      <link rel="shortcut icon" type="image/png" href="{% static 'ico/favicon.png' %}" >
   </head>
   <body>
      <nav class="navbar navbar-expand-sm bg-body-tertiary bg-dark px-2" data-bs-theme="dark">
         <!--Brand Logo-->
         <a class="navbar-brand my-1" href="{% url 'football_quiz:main' %}">
            <img src="{% static 'ico/favicon.png' %}" alt="Logo" width="35" class="d-inline-block align-text-top ">
            <span>Football Quiz</span>
         </a>
         <!--Toogle Button-->
         <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse mb-2" id="navbarSupportedContent">
            <!--Main Navbar-->
            <ul class="navbar-nav me-auto">
               <!--Quiz Section-->
               <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                     aria-expanded="false">
                  Quiz
                  </a>
                  <ul class="dropdown-menu">
                     <li><a class="dropdown-item" href="{% url 'football_quiz:quiz' quiz_type='clubs' %}">Club</a></li>
                     <li><a class="dropdown-item" href="{% url 'football_quiz:quiz' quiz_type='national'%}">National</a></li>
                     <li><a class="dropdown-item" href="{% url 'football_quiz:quiz' quiz_type='stadium' %}">Stadium</a></li>
                     <li><a class="dropdown-item" href="{% url 'football_quiz:quiz' quiz_type='wc' %}">World Cup</a></li>
                  </ul>
               </li>
               <!--Squad Section-->
               <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                     aria-expanded="false">
                  Squad Challenge
                  </a>
                  <ul class="dropdown-menu">
                     <li><a class="dropdown-item" href="{% url 'football_quiz:squad_challange' quiz_type='value squad' %}">Most Value</a>
                     </li>
                     <li><a class="dropdown-item" href="{% url 'football_quiz:squad_challange' quiz_type='goal squad' %}">Most Goal</a>
                     </li>
                     <li><a class="dropdown-item" href="{% url 'football_quiz:squad_challange' quiz_type='assist squad' %}">Most
                        Assist</a>
                     </li>
                     <li><a class="dropdown-item" href="{% url 'football_quiz:squad_challange' quiz_type='yellow squad' %}">Most
                        Yellow</a>
                     </li>
                  </ul>
               </li>
               <!--Rank Section-->
               <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                     aria-expanded="false">
                  Rank
                  </a>
                  <ul class="dropdown-menu">
                     <li><span class="dropdown-header">Quiz Challenge</span></li>
                     <li><a class="dropdown-item" href="{% url 'football_quiz:ranking' quiz_type='clubs' %}">Clubs</a></li>
                     <li><a class="dropdown-item" href="{% url 'football_quiz:ranking' quiz_type='national' %}">Nations</a></li>
                     <li><a class="dropdown-item" href="{% url 'football_quiz:ranking' quiz_type='stadium' %}">Stadiums</a></li>
                     <li><a class="dropdown-item" href="{% url 'football_quiz:ranking' quiz_type='wc' %}">World Cups</a></li>
                     <li>
                        <hr class="dropdown-divider">
                     </li>
                     <li><span class="dropdown-header">Squad Challenge</span></li>
                     <li><a class="dropdown-item" href="{% url 'football_quiz:ranking' quiz_type='value squad' %}">Most Value</a></li>
                     <li><a class="dropdown-item" href="{% url 'football_quiz:ranking' quiz_type='goal squad' %}">Most Score</a></li>
                     <li><a class="dropdown-item" href="{% url 'football_quiz:ranking' quiz_type='assist squad' %}">Most Assist</a></li>
                     <li><a class="dropdown-item" href="{% url 'football_quiz:ranking' quiz_type='yellow squad' %}">Most Yellow</a></li>
                     <li>
                        <hr class="dropdown-divider">
                     </li>
                     <li><a class="dropdown-item" href="{% url 'football_quiz:ranking' quiz_type='all' %}">Best of all</a></li>
                  </ul>
               </li>
            </ul>
            <!--User Section-->
            <ul class="navbar-nav">
               {% if user.is_authenticated %}
               <li class="nav-item">
                  <a class="nav-link fw-bolder text-danger" href="{% url 'football_quiz:profile' user_id=user.id %}">{{user.username}}</a>
               </li>
               <li class="nav-item">
                  <a class="nav-link fw-bolder text-danger" href="{% url 'user:logout_request' %}">Logout</a>
               </li>
               {% else %}
               <li class="nav-item">
                  <a class="nav-link fw-bolder text-danger" href="{% url 'user:login_request' %}">Login</a>
               </li>
               <li class="nav-item">
                  <a class="nav-link fw-bolder text-danger" href="{% url 'user:register_request' %}">Register</a>
               </li>
               {% endif %}
            </ul>
         </div>
      </nav>
      <!--Message Alert-->
      {% if messages %}
      {% for message in messages %}
         {% if forloop.counter == 1 %}
            <div class="alert alert-dismissible fade show my-0 {% if message.tags %}{{ message.tags }}{% endif %}" role="alert">
               {{ message }}
            </div>
         {% endif %}
      {% endfor %}
      {% endif %} 
      <!--Main Content block-->
      {% block content %}
      {% endblock %}
      <!--Footer Section-->

      <footer class="text-center mt-2 d-flex flex-column p-2">
         <div class="col-12">
            <p class="text-muted">© 2023 Football Quiz. All rights reserved.</p>
            <p class="text-muted">Created by Kamil Falkowski</p>
         </div>

         <p class="fw-bold mt-2">Check out my other sites:</p>
         <div class="col-12 d-flex justify-content-around mt-2">
            <a class="logo-text d-block" href="https://airline.falkowskikamil.site"><img class="logo" src="{% static 'airlinesapp.ico' %}" alt="Airlinesapp">AirlinesApp</a>
            <a class="logo-text d-block" href="https://moviescatalogue.falkowskikamil.site"><img class="logo" src="{% static 'moviescatalogue.png' %}" alt="MoviesCatalogue logo">MoviesCatalogue</a>
         </div>

         <p class="fw-bold mt-2">Contact:</p>
         <div class="col-12 d-flex justify-content-around mt-2">
            <a class="logo-text d-block" href="https://github.com/falkowskikamil"><img class="logo" src="{% static 'github.png' %}" alt="Github Logo">Github</a>
            <a class="logo-text d-block" href="https://www.linkedin.com/in/kamil-falkowski-6207a0273/"><img class="logo" src="{% static 'linkedin.png' %}" alt="Linkedin Logo">Linkedin</a>

            </div>
      </footer>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
         integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
   </body>
</html>

quiz/templates/quiz/menu_main.html
{% extends "quiz/index.html" %}
{% block content %}
<div id="carouselId" class="carousel slide" data-bs-ride="carousel">
<div class="carousel-inner">
  <div class="carousel-item active">
<a href="{% url 'football_quiz:main_quiz' %}" class="banner-link main-quiz">
  <div class="mask h-100 d-flex flex-column justify-content-center align-items-center">
    <div class="h-auto">
      <h1 class="text-white m-2 text-center banner-title">Quiz</h1>
    </div>
    <p class="text-center text-white banner-text">
      <strong>Test your knowledge with an exciting quiz challenge!</strong> <br>
      Embark on a journey to showcase your expertise in the realm of football.<br>
      This quiz challenge covers a wide range of competitions, including Clubs, National Teams, Stadiums, and the World Cup. <br>
    </p>
  </div>
</a>
</div>
<div class="carousel-item">
<a href="{% url 'football_quiz:main_squad' %}" class="banner-link main-squad">
  <div class="mask h-100 d-flex flex-column justify-content-center align-items-center">
    <div class="h-auto">
      <h1 class="text-white m-2 text-center banner-title">Squad</h1>
    </div>
    <p class="text-center text-white banner-text">
      <strong>Test your knowledge about football squads!</strong> <br>
      This squad challenge allows you to explore various aspects of different football teams. <br>
      Choose from different types of squads, including the value squad, goal squad, assist squad, and yellow card squad. <br>
    </p>
  </div>
</a>
</div>
<button class="carousel-control-prev" type="button" data-bs-target="#carouselId" data-bs-slide="prev">
  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
  <span class="visually-hidden">Previous</span>
</button>
<button class="carousel-control-next" type="button" data-bs-target="#carouselId" data-bs-slide="next">
  <span class="carousel-control-next-icon" aria-hidden="true"></span>
  <span class="visually-hidden">Next</span>
  </button>
</div>
{% endblock %}

quiz/templates/quiz/menu_quiz.html
{% extends "quiz/index.html" %}{% block title %}Quiz Menu{% endblock%}
{% block content %}

<main id="carouselId" class="carousel slide" data-bs-ride="carousel">
  <ol class="carousel-indicators">
    <li type="button" data-bs-target="#carouselId" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></li>
    <li type="button" data-bs-target="#carouselId" data-bs-slide-to="1" aria-label="Slide 2"></li>
    <li type="button" data-bs-target="#carouselId" data-bs-slide-to="2" aria-label="Slide 3"></li>
    <li type="button" data-bs-target="#carouselId" data-bs-slide-to="3" aria-label="Slide 3"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <section class="carousel-item active">
    <a href="{% url 'football_quiz:quiz' quiz_type='wc' %}" class="banner-link quiz-wc">
      <div class="mask h-100 d-flex flex-column justify-content-center align-items-center">
        <div class="h-auto">
          <h1 class="text-white m-2 text-center banner-title">World Cup</h1>
        </div>
        <p class="text-center text-white banner-text">
          <strong>Test your knowledge about the FIFA World Cup!</strong> <br>
          From July 13, 1930, to December 31, 2022, <br>
          This quiz covers the prestigious FIFA World Cup tournament. <br>
          Discover fascinating facts about the tournament's rich history, memorable moments, and legendary players. <br>
          Challenge yourself with questions about the most appearances, top goal scorers, winning teams, and iconic matches. <br>
          Prove your expertise in the world of the FIFA World Cup and become a true connoisseur of the beautiful game!<br>
        </p>
      </div>
    </a>
  </section>
  <section class="carousel-item">
    <a href="{% url 'football_quiz:quiz' quiz_type='stadium' %}" class="banner-link quiz-stadium">
      <div class="mask h-100 d-flex flex-column justify-content-center align-items-center">
        <div class="h-auto">
          <h1 class="text-white m-2 text-center banner-title">Stadium</h1>
        </div>
        <p class="text-center text-white banner-text">
          <strong>Test your knowledge about stadiums around the world!</strong> <br>
          This quiz covers some of the biggest and most iconic stadiums from various countries. <br>
          Discover which country boasts the most big stadiums and learn about the rich history and cultural significance of these sporting arenas. <br>
          Challenge yourself and prove your expertise in the world of stadiums and their significance in the realm of sports!<br>
        </p>
      </div>
    </a>
    </section>
    <section class="carousel-item">
      <a href="{% url 'football_quiz:quiz' quiz_type='national' %}" class="banner-link quiz-national">
        <div class="mask h-100 d-flex flex-column justify-content-center align-items-center">
          <div class="h-auto">
            <h1 class="text-white m-2 text-center banner-title">National</h1>
          </div>
          <p class="text-center text-white banner-text">
            <strong>Test your knowledge about national football teams!</strong> <br>
            From November 30, 1872, to March 29, 2023, <br>
            This quiz covers national team competitions from all around the world. <br>
            From the historic matches of the FIFA World Cup to regional tournaments like: <br>
            the UEFA European Championship, CONMEBOL Copa America, AFC Asian Cup, CAF Africa Cup of Nations, and CONCACAF Gold Cup,<br>
            Explore the rich history, rivalries, and achievements of national football teams. <br>
            Challenge yourself and prove your expertise in the world of international football competitions!<br>
          </p>
        </div>
      </a>
    </section>
    <section class="carousel-item">
      <a href="{% url 'football_quiz:quiz' quiz_type='clubs' %}" class="banner-link quiz-clubs">
        <div class="mask h-100 d-flex flex-column justify-content-center align-items-center">
          <div class="h-auto">
            <h1 class="text-white m-2 text-center banner-title">Clubs</h1>
          </div>
          <p class="text-center text-white banner-text">
            <strong>Test your knowledge about football clubs!</strong> <br>
            From August 31, 2002, to December 31, 2022, <br>
            This quiz covers top leagues and competitions like <br>
            Bundesliga, FA Cup, Ligue 1, Premier League, La Liga, Serie A, UEFA Champions League, and UEFA Europa League.<br>
            Explore the rich history, rivalries, and achievements of iconic clubs. <br>
            Challenge yourself and prove your expertise in the world of football clubs!<br>
          </p>
        </div>
      </a>
    </section>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselId" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselId" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
    </button>
</main>
{% endblock %}

quiz/templates/quiz/menu_squad.html
{% extends "quiz/index.html" %}{% block title %}Squad Menu{% endblock%}
{% block content %}

<main id="carouselId" class="carousel slide" data-bs-ride="carousel">
  <ol class="carousel-indicators">
    <li type="button" data-bs-target="#carouselId" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></li>
    <li type="button" data-bs-target="#carouselId" data-bs-slide-to="1" aria-label="Slide 2"></li>
    <li type="button" data-bs-target="#carouselId" data-bs-slide-to="2" aria-label="Slide 3"></li>
    <li type="button" data-bs-target="#carouselId" data-bs-slide-to="3" aria-label="Slide 3"></li>
  </ol>
  <div class="carousel-inner">
    <section class="carousel-item active">
      <a href="{% url 'football_quiz:squad_challange' quiz_type='value squad' %}" class="banner-link value-squad">
        <div class="mask h-100 d-flex flex-column justify-content-center align-items-center">
          <div class="h-auto">
            <h1 class="text-white m-2 text-center banner-title">Most Valued Team</h1>
          </div>
          <p class="text-center text-white banner-text">
            <strong>Assemble your ultimate squad of the most valuable football players!</strong> <br>
            In this challenge, you have the task of selecting the 11 most valuable players from a list of 1200 footballers,<br>
            One for each position on the field. Your goal is to create a dream team that consists of the most highly valued players in the world. <br>
            Consider their skills, performance, and market value to make strategic decisions for each position.<br>
            Can you create a lineup that showcases the best of the best? Prepare to test your knowledge and build the ultimate squad of football superstars!
          </p>
        </div>
      </a>
    </section>
    <section class="carousel-item">
      <a href="{% url 'football_quiz:squad_challange' quiz_type='goal squad' %}" class="banner-link goal-squad">
        <div class="mask h-100 d-flex flex-column justify-content-center align-items-center">
          <div class="h-auto">
            <h1 class="text-white m-2 text-center banner-title">Most Highest-scoring Team</h1>
          </div>
          <p class="text-center text-white banner-text">
            <strong>Assemble your ultimate squad of the highest-scoring football players!</strong> <br>
            In this challenge, your task is to select the 11 highest-scoring players for each position on the field from a list of 1200 footballers.<br>
            Your goal is to create a dream team that consists of the most prolific goal scorers in the world. <br>
            Consider their scoring records, playing style, and goal-scoring abilities to make strategic decisions for each position.<br>
            Can you create a lineup that showcases the best of the best when it comes to finding the back of the net?<br>
            Get ready to test your knowledge and build the ultimate squad of football's top goal scorers!
          </p>
        </div>
      </a>
    </section>
    <section class="carousel-item">
      <a href="{% url 'football_quiz:squad_challange' quiz_type='assist squad' %}" class="banner-link assist-squad">
        <div class="mask h-100 d-flex flex-column justify-content-center align-items-center">
          <div class="h-auto">
            <h1 class="text-white m-2 text-center banner-title">Most Assist Team</h1>
          </div>
          <p class="text-center text-white banner-text">
            <strong>Create your ultimate squad of the top assist providers!</strong> <br>
            In this challenge, your mission is to assemble the 11 players who are the best assist providers for each position on the field.<br>
            Your objective is to construct a dream team consisting of the most prolific creators of goals in the world of football. <br>
            Consider their assist records, vision, passing abilities, and playmaking skills to make strategic decisions for each position.<br>
            Can you build a lineup that highlights the finest assist providers? Prepare to put your knowledge to the test and form the ultimate squad of football's top playmakers!
          </p>
        </div>
      </a>
    </section>
    <section class="carousel-item">
      <a href="{% url 'football_quiz:squad_challange' quiz_type='yellow squad' %}" class="banner-link yellow-squad">
        <div class="mask h-100 d-flex flex-column justify-content-center align-items-center">
          <div class="h-auto">
            <h1 class="text-white m-2 text-center banner-title">Most Yellow Team</h1>
          </div>
          <p class="text-center text-white banner-text">
            <strong>Form your ultimate squad of players with the most yellow cards!</strong> <br>
            In this challenge, you have the task of selecting the 11 players who have received the most yellow cards for each position on the field<br>
            Your goal is to create a team consisting of the players who are most notorious for their disciplinary record in the world of football. <br>
            Consider their yellow card statistics, aggressiveness, and playing style to make strategic decisions for each position. <br>
            Can you assemble a lineup that showcases the most caution-prone players? <br>
            Prepare to test your knowledge and build the ultimate squad of football's top card collectors!
          </p>
        </div>
      </a>
    </section>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselId" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselId" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
    </button>
</main>
{% endblock %}

user/templates/user/login.html
{% extends "quiz/index.html" %}{% block title %}Login Form{% endblock %}
{% load static %}
{% block content %}
<main class="container text-center mt-4 p-4 border rounded-5 bg-secondary w-50">
   <form class="vw-25 p-4" action="{% url 'user:login_request' %}", method="POST">
      {% csrf_token %}
      <img class="mb-4" src="{% static 'ico/favicon.png' %}" alt="logo" width="50" height="57">
      <h1 class="h3 mb-3 fw-bolder">Login</h1>
      <div class="form-group">
         <label for="username" class="m-2"><b>User Name</b></label>
         <input id="username" class = "form-control" type="text" placeholder="Enter User Name: " name="username" required> 
         <label for="psw" class="m-2"><b>Password</b></label>
         <input id="psw" class = "form-control" type="password"  placeholder="Enter Password: " name="psw" required> 
      </div>
      <button class="btn btn-primary mt-2" type="submit">Login</button> 
   </form>
</main>
{% endblock %}